<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Ujian>
 */
class UjianFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'nama_ujian' => $this->faker->randomElement([
                'Ujian Kewirausahaan Dasar',
                'Tes Pemahaman Bisnis UMKM',
                'Evaluasi Kewirausahaan Digital',
                'Assessment Entrepreneurship Skills',
                'Kompetensi Manajemen Usaha',
                'Ujian Konsep Kewirausahaan Modern',
                'Tes Pengetahuan Industri Kreatif',
                'Evaluasi Business Plan Development',
                'Uji Kompetensi Digital Marketing',
                'Assessment Financial Literacy',
                'Tes Manajemen Operasional',
                'Evaluasi Strategi Pemasaran',
                'Ujian Leadership Kewirausahaan',
                'Tes Inovasi Produk Jasa',
                'Assessment Risk Management',
                'Ujian Kewirausahaan Sosial',
                'Tes Networking dan Partnership',
                'Evaluasi E-commerce Fundamentals',
                'Uji Kompetensi Supply Chain',
                'Assessment Customer Service',
                'Ujian Branding dan Positioning',
                'Tes Business Analytics',
                'Evaluasi Human Resource Management',
                'Ujian Legal Aspek Usaha',
                'Tes Quality Management',
                'Assessment Sustainable Business',
                'Ujian Business Ethics',
                'Tes Project Management',
                'Evaluasi Digital Transformation',
                'Ujian Market Research',
                'Tes Content Creation Strategy',
                'Assessment SEO dan SEM',
                'Ujian Social Media Marketing',
                'Tes Email Marketing Campaign',
                'Evaluasi Product Development',
                'Ujian Service Design',
                'Tes Customer Experience',
                'Assessment Business Intelligence',
                'Ujian Cloud Computing untuk UMKM',
                'Tes Mobile App Development',
                'Evaluasi Cybersecurity Basics',
                'Ujian Data Privacy Protection',
                'Tes Blockchain Fundamentals',
                'Assessment AI dalam Bisnis',
                'Ujian IoT untuk Usaha Kecil',
                'Tes 5G Technology Applications',
                'Evaluasi Sustainable Practices',
                'Ujian Green Business Model',
                'Tes Circular Economy',
                'Assessment Social Entrepreneurship',
                'Ujian Franchise Management',
                'Tes Licensing Agreement',
                'Evaluasi Intellectual Property',
                'Ujian Business Valuation',
                'Tes Investment Pitching',
                'Assessment Crowdfunding',
                'Ujian Microfinance Management',
                'Tes Islamic Banking',
                'Evaluasi Fintech Solutions',
                'Ujian E-Wallet Integration',
                'Tes Digital Payment Systems',
                'Assessment Revenue Models',
                'Ujian Cost Management',
                'Tes Pricing Strategies',
                'Evaluasi Break Even Analysis',
                'Ujian Cash Flow Management',
                'Tes Budget Planning',
                'Assessment Financial KPIs',
                'Ujian Tax Planning',
                'Tes Accounting Basics',
                'Evaluasi Audit Internal',
                'Ujian Compliance Management',
                'Tes Business Process Optimization',
                'Assessment Change Management',
                'Ujian Crisis Response',
                'Tes Business Continuity',
                'Evaluasi Stakeholder Management',
                'Ujian Team Building',
                'Tes Conflict Resolution',
                'Assessment Negotiation Skills',
                'Ujian Public Speaking',
                'Tes Business Communication',
                'Evaluasi Cross-Cultural Management',
                'Ujian Global Business Trends',
                'Tes Local Market Analysis',
                'Assessment Competitive Intelligence',
                'Ujian SWOT Analysis',
                'Tes PESTEL Analysis',
                'Evaluasi Business Canvas',
                'Ujian Lean Startup Methodology',
                'Tes Agile Business Practices',
                'Assessment Design Thinking',
                'Ujian Prototyping dan MVP',
                'Tes Minimum Viable Product',
                'Evaluasi Market Validation',
                'Ujian Customer Development',
                'Tes Pivot Strategy',
                'Assessment Growth Hacking',
                'Ujian Viral Marketing',
                'Tes Influencer Marketing'
            ]),
            'deskripsi' => $this->faker->randomElement([
                'Ujian ini menguji pemahaman mahasiswa tentang konsep dasar kewirausahaan dan kemampuan mengidentifikasi peluang bisnis.',
                'Tes ini dirancang untuk menilai pengetahuan mahasiswa tentang manajemen operasional dan strategi bisnis UMKM.',
                'Ujian komprehensif mencakup berbagai aspek kewirausahaan dari perencanaan hingga implementasi.',
                'Assessment ini fokus pada kemampuan mahasiswa dalam mengembangkan dan mengelola usaha mikro kecil menengah.',
                'Tes evaluasi kemampuan analitis dan kreatif mahasiswa dalam pengembangan model bisnis inovatif.',
                'Ujian ini menilai pemahaman konsep-konsep modern dalam kewirausahaan digital dan teknologi.',
                'Assessment kemampuan mahasiswa dalam menganalisis pasar dan mengembangkan strategi pemasaran.',
                'Tes kemampuan manajemen keuangan dan perencanaan bisnis untuk usaha skala kecil.',
                'Ujian ini menguji pemahaman tentang aspek hukum dan regulasi dalam berbisnis.',
                'Assessment kemampuan leadership dan manajemen tim dalam konteks kewirausahaan.',
                'Tes kemampuan komunikasi bisnis dan presentasi yang efektif.',
                'Ujian ini mengevaluasi pemahaman tentang tren bisnis global dan lokal.',
                'Assessment kemampuan mahasiswa dalam menggunakan teknologi untuk pengembangan bisnis.',
                'Tes kemampuan analisis data dan pengambilan keputusan bisnis berbasis evidence.',
                'Ujian ini menguji pemahaman tentang praktik bisnis berkelanjutan dan tanggung jawab sosial.',
                'Assessment kemampuan mahasiswa dalam mengelola risiko dan ketidakpastian bisnis.',
                'Tes kemampuan inovasi dan pengembangan produk/jasa yang kompetitif.',
                'Ujian ini menilai pemahaman tentang manajemen hubungan pelanggan dan pelayanan.',
                'Assessment kemampuan mahasiswa dalam membangun merek dan positioning produk.',
                'Tes pemahaman tentang pemasaran digital dan strategi komunikasi online.',
                'Ujian ini menguji kemampuan mahasiswa dalam analisis keuangan dan perencanaan investasi.',
                'Assessment kemampuan manajemen sumber daya manusia dan pengembangan tim.',
                'Tes pemahaman tentang optimasi proses bisnis dan efisiensi operasional.',
                'Ujian ini mengevaluasi kemampuan manajemen perubahan dan adaptasi organisasi.',
                'Assessment kemampuan mahasiswa dalam mengelola krisis dan pemulihan bisnis.',
                'Tes kemampuan komunikasi lintas budaya dan manajemen global.',
                'Ujian ini menguji pemahaman tentang analisis lingkungan bisnis dan kompetisi.',
                'Assessment kemampuan mahasiswa dalam pengembangan rencana bisnis yang komprehensif.',
                'Tes pemahaman tentang metodologi lean startup dan praktik pengembangan bisnis.',
                'Ujian ini mengevaluasi kemampuan berpikir desain dan solusi berorientasi user.',
                'Assessment kemampuan mahasiswa dalam prototyping dan pengujian produk minimum.',
                'Tes kemahaman analisis pasar dan validasi model bisnis.',
                'Ujian ini menguji kemampuan manajemen pertumbuhan dan strategi pemasaran viral.',
                'Assessment kemampuan mahasiswa dalam memanfaatkan media sosial untuk bisnis.',
                'Tes pemahaman tentang pemasaran konten dan strategi komunikasi kreatif.',
                'Ujian ini mengevaluasi kemampuan mahasiswa dalam SEO dan pemasaran mesin pencari.',
                'Assessment kemampuan dalam email marketing dan komunikasi otomatis.',
                'Tes pemahaman tentang pengembangan produk dan inovasi berkelanjutan.',
                'Ujian ini menguji kemampuan dalam desain layanan dan pengalaman pelanggan.',
                'Assessment kemampuan mahasiswa dalam analisis bisnis dan intelligence.',
                'Tes pemahaman tentang teknologi cloud dan implementasi bisnis digital.',
                'Ujian ini mengevaluasi kemampuan dalam pengembangan aplikasi mobile untuk bisnis.',
                'Assessment pemahaman dasar keamanan siber dan perlindungan data bisnis.',
                'Tes kemahaman tentang privasi data dan kepatuhan regulasi digital.',
                'Ujian ini menguji pemahaman tentang teknologi blockchain dan aplikasi bisnis.',
                'Assessment kemampuan dalam menggunakan AI dan machine learning untuk bisnis.',
                'Tes pemahaman tentang IoT dan aplikasi teknologi sensor untuk usaha.',
                'Ujian ini mengevaluasi pemahaman tentang teknologi 5G dan implikasi bisnis.',
                'Assessment pemahaman tentang praktik bisnis berkelanjutan dan ekonomi sirkular.',
                'Ujian ini menguji kemampuan dalam mengembangkan model bisnis hijau dan berkelanjutan.',
                'Tes pemahaman tentang ekonomi sirkular dan praktik daur ulang produk.',
                'Assessment kemampuan dalam kewirausahaan sosial dan dampak positif masyarakat.',
                'Ujian ini mengevaluasi kemampuan dalam manajemen waralaba dan kemitraan.',
                'Tes pemahaman tentang perjanjian lisensi dan hak kekayaan intelektual.',
                'Ujian ini menguji kemampuan dalam manajemen merek dan positioning strategis.',
                'Assessment kemampuan dalam penilaian bisnis dan strategi investasi.',
                'Tes pemahaman tentang crowdfunding dan pembiayaan alternatif.',
                'Ujian ini mengevaluasi kemampuan dalam manajemen mikrofinance dan inklusi keuangan.',
                'Tes pemahaman tentang perbankan syariah dan produk keuangan islami.',
                'Ujian ini menguji pemahaman tentang teknologi finansial dan inovasi pembayaran.',
                'Assessment kemampuan dalam integrasi e-wallet dan sistem pembayaran digital.',
                'Tes pemahaman tentang model pendapatan dan strategi monetisasi.',
                'Ujian ini mengevaluasi kemampuan dalam manajemen biaya dan strategi pricing.',
                'Tes pemahaman tentang analisis break even dan proyeksi keuangan.',
                'Ujian ini menguji kemampuan dalam manajemen arus kas dan likuiditas.',
                'Tes pemahaman tentang perencanaan anggaran dan kontrol keuangan.',
                'Assessment kemampuan dalam pengelolaan KPI keuangan dan performa bisnis.',
                'Ujian ini mengevaluasi pemahaman tentang perencanaan pajak dan optimasi fiskal.',
                'Tes pemahaman dasar akuntansi dan pelaporan keuangan bisnis.',
                'Ujian ini menguji kemampuan dalam audit internal dan kontrol manajemen.',
                'Tes pemahaman tentang kepatuhan regulasi dan manajemen risiko hukum.',
                'Ujian ini mengevaluasi kemampuan dalam optimasi proses dan lean management.',
                'Assessment kemampuan adaptif terhadap perubahan lingkungan bisnis.',
                'Tes kemampuan dalam manajemen krisis dan strategi pemulihan.',
                'Ujian ini menguji kemampuan dalam manajemen hubungan dengan stakeholder kunci.',
                'Tes pemahaman tentang manajemen tim dan dinamika kelompok kerja.',
                'Ujian ini mengevaluasi kemampuan dalam negosiasi dan resolusi konflik.',
                'Assessment kemampuan komunikasi publik dan presentasi bisnis.',
                'Tes kemampuan komunikasi bisnis efektif dan profesional.',
                'Ujian ini menguji pemahaman tentang manajemen lintas budaya dan globalisasi.',
                'Tes pemahaman tentang tren bisnis global dan adaptasi lokal.'
            ]),
            'durasi_menit' => $this->faker->numberBetween(30, 120),
            'is_active' => true,
            'created_at' => $this->faker->dateTimeBetween('-1 year', 'now'),
            'updated_at' => now(),
        ];
    }
}
